name: Test coverage

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev
    paths-ignore:
      - 'docs/**'
      - 'spec/**'

jobs:
  collect-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true

    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features --no-fail-fast
      env:
        CARGO_INCREMENTAL: 0
        RUSTC_BOOTSTRAP: 1
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests"
        RUSTDOCFLAGS: "-Cpanic=abort"

    - name: Collect test coverage data
      uses: actions-rs/grcov@d7fbf3f
      id: coverage
      with:
        args: >
            -t lcov
            --llvm
            --branch
            --ignore-not-existing
            --ignore "/*"
            --ignore "tests/*"
            -o ./target/lcov.info
            ./target/debug/
    
    - name: Upload coverage data to Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./target/lcov.info
