name: Support no_std

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  no_std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: riscv64gc-unknown-none-elf
        override: true

    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features -F aes-cbc,aes-kw,aes-gcm,chacha,ed25519,x25519,rand,aes,blake2b,ternary_hashes,curl-p,ternary_signatures,sha,keccak,hmac,pbkdf2,bip39,bip39-en,bip39-jp,slip10,cipher,ternary_encoding,age,secp256k1,serde --release --target=riscv64gc-unknown-none-elf --manifest-path Cargo.toml
